# Site settings
title: Andrew Paradi The Summer 2016 Intern You Deserve
email: me@andrewparadi.com
description: > # this means to ignore newlines until "baseurl:"
  Andrew's new Jekyll Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewparadi.github.io" # the base hostname & protocol for your site
#Social
twitter_username: Andrew_Paradi
github_username:  andrewparadi
linkedin_username: andrewparadi
youtube_username: AndrewParadi
phone: 19055108904
phonef: +1 (905) 510-8904
loc_city: Waterloo
loc_country: Canada
resume_file: AndrewParadiResume.pdf
pgp_key_file: AndrewParadiPGP.asc
pgp_fingerprint_file: AndrewParadiPGPFingerprint.txt

# Build settings
markdown: kramdown

host: 0.0.0.0
port: 4000
