# Site settings
title: Andrew Paradi The Summer 2016 Intern You Deserve
email: andrewparadi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Andrew's new Jekyll Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewparadi.github.io" # the base hostname & protocol for your site
twitter_username: andrew_paradi
github_username:  andrewparadi

# Build settings
markdown: kramdown

host: 0.0.0.0
port: 4000
